# Generated by Django 6.0 on 2026-01-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=150)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('responsavel', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('servico', models.CharField(choices=[('medicina', 'Medicina Ocupacional'), ('seguranca', 'Segurança do Trabalho'), ('treinamentos', 'Treinamentos')], max_length=20)),
                ('mensagem', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('contato', 'Em contato'), ('orcamento', 'Orçamento enviado'), ('fechado', 'Fechado')], default='novo', max_length=20)),
                ('origem', models.CharField(default='site', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
