# Generated by Django 6.0.1 on 2026-01-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='empresa',
            field=models.CharField(max_length=150, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='mensagem',
            field=models.TextField(blank=True, verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='origem',
            field=models.CharField(default='site', max_length=50, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='responsavel',
            field=models.CharField(max_length=150, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='servico',
            field=models.CharField(choices=[('medicina', 'Medicina Ocupacional'), ('seguranca', 'Segurança do Trabalho'), ('treinamentos', 'Treinamentos')], max_length=20, verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('contato', 'Em contato'), ('orcamento', 'Orçamento enviado'), ('fechado', 'Fechado')], default='novo', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
