# Generated by Django 6.0.5 on 2026-05-06 15:08

import django.core.validators
import institucional.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0002_alter_lead_cnpj_alter_lead_criado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encaminhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('idade', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Idade')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('empresa', models.CharField(max_length=150, verbose_name='Empresa')),
                ('funcao', models.CharField(max_length=120, verbose_name='Função')),
                ('setor', models.CharField(max_length=120, verbose_name='Setor')),
                ('data_admissao', models.DateField(verbose_name='Data de admissão')),
                ('tipo_exame', models.CharField(choices=[('admissional', 'Admissional'), ('periodico', 'Periódico'), ('demissional', 'Demissional'), ('retorno_trabalho', 'Retorno ao trabalho'), ('mudanca_risco', 'Mudança de risco')], max_length=30, verbose_name='Tipo de exame')),
                ('pcmso', models.FileField(upload_to='encaminhamentos/pcmso/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Envie um arquivo PCMSO nos formatos PDF, JPG, JPEG ou PNG.'), institucional.models.validar_tamanho_pcmso], verbose_name='PCMSO')),
                ('docx_gerado', models.FileField(blank=True, null=True, upload_to='encaminhamentos/docx/', verbose_name='Documento DOCX gerado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Encaminhamento',
                'verbose_name_plural': 'Encaminhamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
