# Generated by Django 6.0.5 on 2026-05-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0003_encaminhamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaminhamento',
            name='acuidade_visual',
            field=models.BooleanField(default=False, verbose_name='Acuidade visual'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='audiometria',
            field=models.BooleanField(default=False, verbose_name='Audiometria'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='avaliacao_psicossocial',
            field=models.BooleanField(default=False, verbose_name='Avaliação psicossocial'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='eletrocardiograma',
            field=models.BooleanField(default=False, verbose_name='Eletrocardiograma'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='eletroencefalograma',
            field=models.BooleanField(default=False, verbose_name='Eletroencefalograma'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='espirometria',
            field=models.BooleanField(default=False, verbose_name='Espirometria'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='exame_clinico',
            field=models.BooleanField(default=False, verbose_name='Exame clínico'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='glicemia',
            field=models.BooleanField(default=False, verbose_name='Glicemia'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='hemograma',
            field=models.BooleanField(default=False, verbose_name='Hemograma'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='raio_x_torax',
            field=models.BooleanField(default=False, verbose_name='Raio-X tórax'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='teste_romberg',
            field=models.BooleanField(default=False, verbose_name='Teste de Romberg'),
        ),
    ]
