# Generated by Django 6.0.5 on 2026-05-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0004_encaminhamento_acuidade_visual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaminhamento',
            name='descricao_outro_exame',
            field=models.CharField(blank=True, max_length=150, verbose_name='Descrição do outro exame'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='outro_exame',
            field=models.BooleanField(default=False, verbose_name='Outro exame'),
        ),
    ]
