# Generated by Django 6.0.5 on 2026-05-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0005_encaminhamento_descricao_outro_exame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaminhamento',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='endereco_empresa',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço da empresa'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='nome_emitente',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do emitente'),
        ),
    ]
