# Generated by Django 6.0.5 on 2026-05-07 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0006_encaminhamento_cnpj_encaminhamento_endereco_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaminhamento',
            name='acido_hipurico',
            field=models.BooleanField(default=False, verbose_name='Ácido hipúrico'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='acido_metil_hipurico',
            field=models.BooleanField(default=False, verbose_name='Ácido metil hipúrico'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='data_encaminhamento',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data do encaminhamento'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='grupo_sanguineo_fator_rh',
            field=models.BooleanField(default=False, verbose_name='Grupo sanguíneo/fator RH'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='riscos_ocupacionais',
            field=models.TextField(blank=True, verbose_name='Riscos ocupacionais'),
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='audiometria',
            field=models.BooleanField(default=False, verbose_name='Audiometria tonal'),
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='glicemia',
            field=models.BooleanField(default=False, verbose_name='Glicemia em jejum'),
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='hemograma',
            field=models.BooleanField(default=False, verbose_name='Hemograma completo com plaquetas'),
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='tipo_exame',
            field=models.CharField(choices=[('admissional', 'Admissional'), ('periodico', 'Periódico'), ('demissional', 'Demissional'), ('retorno_trabalho', 'Retorno ao trabalho'), ('mudanca_funcao', 'Mudança de função'), ('mudanca_risco', 'Mudança de risco')], max_length=30, verbose_name='Tipo de exame'),
        ),
    ]
