# Generated by Django 6.0.5 on 2026-05-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0007_encaminhamento_acido_hipurico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaminhamento',
            name='raio_x_torax',
            field=models.BooleanField(default=False, verbose_name='Raio X tórax padrão OIT'),
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='teste_romberg',
            field=models.BooleanField(default=False, verbose_name='Teste de equilíbrio/Romberg'),
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='tipo_exame',
            field=models.CharField(choices=[('admissional', 'Admissional'), ('periodico', 'Periódico'), ('demissional', 'Demissional'), ('retorno_trabalho', 'Retorno ao trabalho'), ('mudanca_funcao', 'Mudança de função')], max_length=30, verbose_name='Tipo de exame'),
        ),
    ]
