# Generated by Django 6.0.5 on 2026-05-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0008_alter_encaminhamento_raio_x_torax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaminhamento',
            name='email_enviado',
            field=models.BooleanField(default=False, verbose_name='E-mail enviado'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido'), ('agendado', 'Agendado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
