# Generated by Django 6.0.5 on 2026-05-08 10:36

import django.core.validators
import institucional.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0009_encaminhamento_email_enviado_encaminhamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaminhamento',
            name='pcmso',
            field=models.FileField(blank=True, upload_to='encaminhamentos/pcmso/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Arquivo inválido. Envie apenas PDF, JPG, JPEG ou PNG.'), institucional.models.validar_tamanho_pcmso], verbose_name='PCMSO'),
        ),
    ]
